import EventEmitter from '../utils/emitter';

// A proxy that listens/emits to events in regards to one xi view.
export default class ViewProxy extends EventEmitter {

  // Our unique view instance id.
  id: number;

  // The view's id generated by xi-core.
  viewId: string;

  // A reference to the our Core wrapper.
  core: any;

  constructor(core, id, viewId) {
    super();

    // Reference to the main core module.
    this.core = core;

    this.id = id;
    this.viewId = viewId;
  }

  send(method: string, params?: any = {}) {
    params.view_id = this.viewId;
    this.core.send(method, params);
  }
}


